// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: code_battle.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_event_unspecified EventType = 0
	EventType_code_battle       EventType = 1
	EventType_workshop          EventType = 2
	EventType_seminar           EventType = 3
	EventType_social            EventType = 4
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "event_unspecified",
		1: "code_battle",
		2: "workshop",
		3: "seminar",
		4: "social",
	}
	EventType_value = map[string]int32{
		"event_unspecified": 0,
		"code_battle":       1,
		"workshop":          2,
		"seminar":           3,
		"social":            4,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_code_battle_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_code_battle_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_code_battle_proto_rawDescGZIP(), []int{0}
}

type SubmissionStatus int32

const (
	SubmissionStatus_submission_unspecified SubmissionStatus = 0
	SubmissionStatus_pending                SubmissionStatus = 1
	SubmissionStatus_accepted               SubmissionStatus = 2
	SubmissionStatus_wrong_answer           SubmissionStatus = 3
	SubmissionStatus_limit_exceeded         SubmissionStatus = 4
	SubmissionStatus_runtime_error          SubmissionStatus = 5
	SubmissionStatus_compilation_error      SubmissionStatus = 6
)

// Enum value maps for SubmissionStatus.
var (
	SubmissionStatus_name = map[int32]string{
		0: "submission_unspecified",
		1: "pending",
		2: "accepted",
		3: "wrong_answer",
		4: "limit_exceeded",
		5: "runtime_error",
		6: "compilation_error",
	}
	SubmissionStatus_value = map[string]int32{
		"submission_unspecified": 0,
		"pending":                1,
		"accepted":               2,
		"wrong_answer":           3,
		"limit_exceeded":         4,
		"runtime_error":          5,
		"compilation_error":      6,
	}
)

func (x SubmissionStatus) Enum() *SubmissionStatus {
	p := new(SubmissionStatus)
	*p = x
	return p
}

func (x SubmissionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubmissionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_code_battle_proto_enumTypes[1].Descriptor()
}

func (SubmissionStatus) Type() protoreflect.EnumType {
	return &file_code_battle_proto_enumTypes[1]
}

func (x SubmissionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubmissionStatus.Descriptor instead.
func (SubmissionStatus) EnumDescriptor() ([]byte, []int) {
	return file_code_battle_proto_rawDescGZIP(), []int{1}
}

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageIndex     int32                  `protobuf:"varint,2,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_code_battle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_code_battle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_code_battle_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationRequest) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

type PaginationResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PageSize        int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageIndex       int32                  `protobuf:"varint,2,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	TotalPages      int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	HasNextPage     int32                  `protobuf:"varint,4,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	HasPreviousPage int32                  `protobuf:"varint,5,opt,name=has_previous_page,json=hasPreviousPage,proto3" json:"has_previous_page,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaginationResult) Reset() {
	*x = PaginationResult{}
	mi := &file_code_battle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResult) ProtoMessage() {}

func (x *PaginationResult) ProtoReflect() protoreflect.Message {
	mi := &file_code_battle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResult.ProtoReflect.Descriptor instead.
func (*PaginationResult) Descriptor() ([]byte, []int) {
	return file_code_battle_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationResult) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationResult) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *PaginationResult) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *PaginationResult) GetHasNextPage() int32 {
	if x != nil {
		return x.HasNextPage
	}
	return 0
}

func (x *PaginationResult) GetHasPreviousPage() int32 {
	if x != nil {
		return x.HasPreviousPage
	}
	return 0
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_code_battle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_code_battle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_code_battle_proto_rawDescGZIP(), []int{2}
}

func (x *Status) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Status) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          EventType              `protobuf:"varint,4,opt,name=type,proto3,enum=code_battle.EventType" json:"type,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_code_battle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_code_battle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_code_battle_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_event_unspecified
}

func (x *Event) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Event) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type GetEventsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PaginationRequest *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination_request,json=paginationRequest,proto3" json:"pagination_request,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_code_battle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_code_battle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_code_battle_proto_rawDescGZIP(), []int{4}
}

func (x *GetEventsRequest) GetPaginationRequest() *PaginationRequest {
	if x != nil {
		return x.PaginationRequest
	}
	return nil
}

type GetEventsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PaginationResult *PaginationResult      `protobuf:"bytes,2,opt,name=pagination_result,json=paginationResult,proto3" json:"pagination_result,omitempty"`
	Events           []*Event               `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_code_battle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_code_battle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_code_battle_proto_rawDescGZIP(), []int{5}
}

func (x *GetEventsResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetEventsResponse) GetPaginationResult() *PaginationResult {
	if x != nil {
		return x.PaginationResult
	}
	return nil
}

func (x *GetEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Submission struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CodeProblemId    string                 `protobuf:"bytes,3,opt,name=code_problem_id,json=codeProblemId,proto3" json:"code_problem_id,omitempty"`
	LanguageId       string                 `protobuf:"bytes,4,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`
	EventId          string                 `protobuf:"bytes,5,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	RoomId           string                 `protobuf:"bytes,6,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	CodeSubmitted    string                 `protobuf:"bytes,7,opt,name=code_submitted,json=codeSubmitted,proto3" json:"code_submitted,omitempty"`
	Status           SubmissionStatus       `protobuf:"varint,8,opt,name=status,proto3,enum=code_battle.SubmissionStatus" json:"status,omitempty"`
	ExecutionTimeMs  int32                  `protobuf:"varint,9,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	SubmittedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	SubmittedGuildId string                 `protobuf:"bytes,11,opt,name=submitted_guild_id,json=submittedGuildId,proto3" json:"submitted_guild_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Submission) Reset() {
	*x = Submission{}
	mi := &file_code_battle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Submission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Submission) ProtoMessage() {}

func (x *Submission) ProtoReflect() protoreflect.Message {
	mi := &file_code_battle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Submission.ProtoReflect.Descriptor instead.
func (*Submission) Descriptor() ([]byte, []int) {
	return file_code_battle_proto_rawDescGZIP(), []int{6}
}

func (x *Submission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Submission) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Submission) GetCodeProblemId() string {
	if x != nil {
		return x.CodeProblemId
	}
	return ""
}

func (x *Submission) GetLanguageId() string {
	if x != nil {
		return x.LanguageId
	}
	return ""
}

func (x *Submission) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Submission) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Submission) GetCodeSubmitted() string {
	if x != nil {
		return x.CodeSubmitted
	}
	return ""
}

func (x *Submission) GetStatus() SubmissionStatus {
	if x != nil {
		return x.Status
	}
	return SubmissionStatus_submission_unspecified
}

func (x *Submission) GetExecutionTimeMs() int32 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *Submission) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

func (x *Submission) GetSubmittedGuildId() string {
	if x != nil {
		return x.SubmittedGuildId
	}
	return ""
}

type SubmitCodeSolutionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CodeProblemId    string                 `protobuf:"bytes,2,opt,name=code_problem_id,json=codeProblemId,proto3" json:"code_problem_id,omitempty"`
	LanguageId       string                 `protobuf:"bytes,3,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`
	EventId          string                 `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	RoomId           string                 `protobuf:"bytes,5,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	CodeSubmitted    string                 `protobuf:"bytes,6,opt,name=code_submitted,json=codeSubmitted,proto3" json:"code_submitted,omitempty"`
	SubmittedGuildId string                 `protobuf:"bytes,7,opt,name=submitted_guild_id,json=submittedGuildId,proto3" json:"submitted_guild_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubmitCodeSolutionRequest) Reset() {
	*x = SubmitCodeSolutionRequest{}
	mi := &file_code_battle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCodeSolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCodeSolutionRequest) ProtoMessage() {}

func (x *SubmitCodeSolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_code_battle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCodeSolutionRequest.ProtoReflect.Descriptor instead.
func (*SubmitCodeSolutionRequest) Descriptor() ([]byte, []int) {
	return file_code_battle_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitCodeSolutionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitCodeSolutionRequest) GetCodeProblemId() string {
	if x != nil {
		return x.CodeProblemId
	}
	return ""
}

func (x *SubmitCodeSolutionRequest) GetLanguageId() string {
	if x != nil {
		return x.LanguageId
	}
	return ""
}

func (x *SubmitCodeSolutionRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SubmitCodeSolutionRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SubmitCodeSolutionRequest) GetCodeSubmitted() string {
	if x != nil {
		return x.CodeSubmitted
	}
	return ""
}

func (x *SubmitCodeSolutionRequest) GetSubmittedGuildId() string {
	if x != nil {
		return x.SubmittedGuildId
	}
	return ""
}

type SubmitCodeSolutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Submission    *Submission            `protobuf:"bytes,2,opt,name=submission,proto3" json:"submission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitCodeSolutionResponse) Reset() {
	*x = SubmitCodeSolutionResponse{}
	mi := &file_code_battle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCodeSolutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCodeSolutionResponse) ProtoMessage() {}

func (x *SubmitCodeSolutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_code_battle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCodeSolutionResponse.ProtoReflect.Descriptor instead.
func (*SubmitCodeSolutionResponse) Descriptor() ([]byte, []int) {
	return file_code_battle_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitCodeSolutionResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SubmitCodeSolutionResponse) GetSubmission() *Submission {
	if x != nil {
		return x.Submission
	}
	return nil
}

type GetUserSubmissionsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PaginationRequest *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination_request,json=paginationRequest,proto3" json:"pagination_request,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetUserSubmissionsRequest) Reset() {
	*x = GetUserSubmissionsRequest{}
	mi := &file_code_battle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSubmissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSubmissionsRequest) ProtoMessage() {}

func (x *GetUserSubmissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_code_battle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSubmissionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserSubmissionsRequest) Descriptor() ([]byte, []int) {
	return file_code_battle_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserSubmissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserSubmissionsRequest) GetPaginationRequest() *PaginationRequest {
	if x != nil {
		return x.PaginationRequest
	}
	return nil
}

type GetUserSubmissionsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PaginationResult *PaginationResult      `protobuf:"bytes,2,opt,name=pagination_result,json=paginationResult,proto3" json:"pagination_result,omitempty"`
	Submissions      []*Submission          `protobuf:"bytes,3,rep,name=submissions,proto3" json:"submissions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetUserSubmissionsResponse) Reset() {
	*x = GetUserSubmissionsResponse{}
	mi := &file_code_battle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSubmissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSubmissionsResponse) ProtoMessage() {}

func (x *GetUserSubmissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_code_battle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSubmissionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserSubmissionsResponse) Descriptor() ([]byte, []int) {
	return file_code_battle_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserSubmissionsResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetUserSubmissionsResponse) GetPaginationResult() *PaginationResult {
	if x != nil {
		return x.PaginationResult
	}
	return nil
}

func (x *GetUserSubmissionsResponse) GetSubmissions() []*Submission {
	if x != nil {
		return x.Submissions
	}
	return nil
}

var File_code_battle_proto protoreflect.FileDescriptor

const file_code_battle_proto_rawDesc = "" +
	"\n" +
	"\x11code_battle.proto\x12\vcode_battle\x1a\x1fgoogle/protobuf/timestamp.proto\"O\n" +
	"\x11PaginationRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_index\x18\x02 \x01(\x05R\tpageIndex\"\xbf\x01\n" +
	"\x10PaginationResult\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_index\x18\x02 \x01(\x05R\tpageIndex\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\x12\"\n" +
	"\rhas_next_page\x18\x04 \x01(\x05R\vhasNextPage\x12*\n" +
	"\x11has_previous_page\x18\x05 \x01(\x05R\x0fhasPreviousPage\"a\n" +
	"\x06Status\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xed\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12*\n" +
	"\x04type\x18\x04 \x01(\x0e2\x16.code_battle.EventTypeR\x04type\x129\n" +
	"\n" +
	"start_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"a\n" +
	"\x10GetEventsRequest\x12M\n" +
	"\x12pagination_request\x18\x01 \x01(\v2\x1e.code_battle.PaginationRequestR\x11paginationRequest\"\xb8\x01\n" +
	"\x11GetEventsResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.code_battle.StatusR\x06status\x12J\n" +
	"\x11pagination_result\x18\x02 \x01(\v2\x1d.code_battle.PaginationResultR\x10paginationResult\x12*\n" +
	"\x06events\x18\x03 \x03(\v2\x12.code_battle.EventR\x06events\"\xa9\x03\n" +
	"\n" +
	"Submission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12&\n" +
	"\x0fcode_problem_id\x18\x03 \x01(\tR\rcodeProblemId\x12\x1f\n" +
	"\vlanguage_id\x18\x04 \x01(\tR\n" +
	"languageId\x12\x19\n" +
	"\bevent_id\x18\x05 \x01(\tR\aeventId\x12\x17\n" +
	"\aroom_id\x18\x06 \x01(\tR\x06roomId\x12%\n" +
	"\x0ecode_submitted\x18\a \x01(\tR\rcodeSubmitted\x125\n" +
	"\x06status\x18\b \x01(\x0e2\x1d.code_battle.SubmissionStatusR\x06status\x12*\n" +
	"\x11execution_time_ms\x18\t \x01(\x05R\x0fexecutionTimeMs\x12=\n" +
	"\fsubmitted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\x12,\n" +
	"\x12submitted_guild_id\x18\v \x01(\tR\x10submittedGuildId\"\x86\x02\n" +
	"\x19SubmitCodeSolutionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x0fcode_problem_id\x18\x02 \x01(\tR\rcodeProblemId\x12\x1f\n" +
	"\vlanguage_id\x18\x03 \x01(\tR\n" +
	"languageId\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\tR\aeventId\x12\x17\n" +
	"\aroom_id\x18\x05 \x01(\tR\x06roomId\x12%\n" +
	"\x0ecode_submitted\x18\x06 \x01(\tR\rcodeSubmitted\x12,\n" +
	"\x12submitted_guild_id\x18\a \x01(\tR\x10submittedGuildId\"\x82\x01\n" +
	"\x1aSubmitCodeSolutionResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.code_battle.StatusR\x06status\x127\n" +
	"\n" +
	"submission\x18\x02 \x01(\v2\x17.code_battle.SubmissionR\n" +
	"submission\"\x83\x01\n" +
	"\x19GetUserSubmissionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12M\n" +
	"\x12pagination_request\x18\x02 \x01(\v2\x1e.code_battle.PaginationRequestR\x11paginationRequest\"\xd0\x01\n" +
	"\x1aGetUserSubmissionsResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.code_battle.StatusR\x06status\x12J\n" +
	"\x11pagination_result\x18\x02 \x01(\v2\x1d.code_battle.PaginationResultR\x10paginationResult\x129\n" +
	"\vsubmissions\x18\x03 \x03(\v2\x17.code_battle.SubmissionR\vsubmissions*Z\n" +
	"\tEventType\x12\x15\n" +
	"\x11event_unspecified\x10\x00\x12\x0f\n" +
	"\vcode_battle\x10\x01\x12\f\n" +
	"\bworkshop\x10\x02\x12\v\n" +
	"\aseminar\x10\x03\x12\n" +
	"\n" +
	"\x06social\x10\x04*\x99\x01\n" +
	"\x10SubmissionStatus\x12\x1a\n" +
	"\x16submission_unspecified\x10\x00\x12\v\n" +
	"\apending\x10\x01\x12\f\n" +
	"\baccepted\x10\x02\x12\x10\n" +
	"\fwrong_answer\x10\x03\x12\x12\n" +
	"\x0elimit_exceeded\x10\x04\x12\x11\n" +
	"\rruntime_error\x10\x05\x12\x15\n" +
	"\x11compilation_error\x10\x062\xad\x02\n" +
	"\x11CodeBattleService\x12J\n" +
	"\tGetEvents\x12\x1d.code_battle.GetEventsRequest\x1a\x1e.code_battle.GetEventsResponse\x12e\n" +
	"\x12SubmitCodeSolution\x12&.code_battle.SubmitCodeSolutionRequest\x1a'.code_battle.SubmitCodeSolutionResponse\x12e\n" +
	"\x12GetUserSubmissions\x12&.code_battle.GetUserSubmissionsRequest\x1a'.code_battle.GetUserSubmissionsResponseB>Z<github.com/FA25SE050-RogueLearn/RogueLearn.CodeBattle/protosb\x06proto3"

var (
	file_code_battle_proto_rawDescOnce sync.Once
	file_code_battle_proto_rawDescData []byte
)

func file_code_battle_proto_rawDescGZIP() []byte {
	file_code_battle_proto_rawDescOnce.Do(func() {
		file_code_battle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_code_battle_proto_rawDesc), len(file_code_battle_proto_rawDesc)))
	})
	return file_code_battle_proto_rawDescData
}

var file_code_battle_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_code_battle_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_code_battle_proto_goTypes = []any{
	(EventType)(0),                     // 0: code_battle.EventType
	(SubmissionStatus)(0),              // 1: code_battle.SubmissionStatus
	(*PaginationRequest)(nil),          // 2: code_battle.PaginationRequest
	(*PaginationResult)(nil),           // 3: code_battle.PaginationResult
	(*Status)(nil),                     // 4: code_battle.Status
	(*Event)(nil),                      // 5: code_battle.Event
	(*GetEventsRequest)(nil),           // 6: code_battle.GetEventsRequest
	(*GetEventsResponse)(nil),          // 7: code_battle.GetEventsResponse
	(*Submission)(nil),                 // 8: code_battle.Submission
	(*SubmitCodeSolutionRequest)(nil),  // 9: code_battle.SubmitCodeSolutionRequest
	(*SubmitCodeSolutionResponse)(nil), // 10: code_battle.SubmitCodeSolutionResponse
	(*GetUserSubmissionsRequest)(nil),  // 11: code_battle.GetUserSubmissionsRequest
	(*GetUserSubmissionsResponse)(nil), // 12: code_battle.GetUserSubmissionsResponse
	(*timestamppb.Timestamp)(nil),      // 13: google.protobuf.Timestamp
}
var file_code_battle_proto_depIdxs = []int32{
	0,  // 0: code_battle.Event.type:type_name -> code_battle.EventType
	13, // 1: code_battle.Event.start_date:type_name -> google.protobuf.Timestamp
	13, // 2: code_battle.Event.end_date:type_name -> google.protobuf.Timestamp
	2,  // 3: code_battle.GetEventsRequest.pagination_request:type_name -> code_battle.PaginationRequest
	4,  // 4: code_battle.GetEventsResponse.status:type_name -> code_battle.Status
	3,  // 5: code_battle.GetEventsResponse.pagination_result:type_name -> code_battle.PaginationResult
	5,  // 6: code_battle.GetEventsResponse.events:type_name -> code_battle.Event
	1,  // 7: code_battle.Submission.status:type_name -> code_battle.SubmissionStatus
	13, // 8: code_battle.Submission.submitted_at:type_name -> google.protobuf.Timestamp
	4,  // 9: code_battle.SubmitCodeSolutionResponse.status:type_name -> code_battle.Status
	8,  // 10: code_battle.SubmitCodeSolutionResponse.submission:type_name -> code_battle.Submission
	2,  // 11: code_battle.GetUserSubmissionsRequest.pagination_request:type_name -> code_battle.PaginationRequest
	4,  // 12: code_battle.GetUserSubmissionsResponse.status:type_name -> code_battle.Status
	3,  // 13: code_battle.GetUserSubmissionsResponse.pagination_result:type_name -> code_battle.PaginationResult
	8,  // 14: code_battle.GetUserSubmissionsResponse.submissions:type_name -> code_battle.Submission
	6,  // 15: code_battle.CodeBattleService.GetEvents:input_type -> code_battle.GetEventsRequest
	9,  // 16: code_battle.CodeBattleService.SubmitCodeSolution:input_type -> code_battle.SubmitCodeSolutionRequest
	11, // 17: code_battle.CodeBattleService.GetUserSubmissions:input_type -> code_battle.GetUserSubmissionsRequest
	7,  // 18: code_battle.CodeBattleService.GetEvents:output_type -> code_battle.GetEventsResponse
	10, // 19: code_battle.CodeBattleService.SubmitCodeSolution:output_type -> code_battle.SubmitCodeSolutionResponse
	12, // 20: code_battle.CodeBattleService.GetUserSubmissions:output_type -> code_battle.GetUserSubmissionsResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_code_battle_proto_init() }
func file_code_battle_proto_init() {
	if File_code_battle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_code_battle_proto_rawDesc), len(file_code_battle_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_code_battle_proto_goTypes,
		DependencyIndexes: file_code_battle_proto_depIdxs,
		EnumInfos:         file_code_battle_proto_enumTypes,
		MessageInfos:      file_code_battle_proto_msgTypes,
	}.Build()
	File_code_battle_proto = out.File
	file_code_battle_proto_goTypes = nil
	file_code_battle_proto_depIdxs = nil
}
