// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: api/proto/code_battle.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CodeBattleService_GetEvents_FullMethodName = "/code_battle.CodeBattleService/GetEvents"
)

// CodeBattleServiceClient is the client API for CodeBattleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CodeBattleServiceClient interface {
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
}

type codeBattleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCodeBattleServiceClient(cc grpc.ClientConnInterface) CodeBattleServiceClient {
	return &codeBattleServiceClient{cc}
}

func (c *codeBattleServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, CodeBattleService_GetEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CodeBattleServiceServer is the server API for CodeBattleService service.
// All implementations must embed UnimplementedCodeBattleServiceServer
// for forward compatibility.
type CodeBattleServiceServer interface {
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
	mustEmbedUnimplementedCodeBattleServiceServer()
}

// UnimplementedCodeBattleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCodeBattleServiceServer struct{}

func (UnimplementedCodeBattleServiceServer) GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedCodeBattleServiceServer) mustEmbedUnimplementedCodeBattleServiceServer() {}
func (UnimplementedCodeBattleServiceServer) testEmbeddedByValue()                           {}

// UnsafeCodeBattleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CodeBattleServiceServer will
// result in compilation errors.
type UnsafeCodeBattleServiceServer interface {
	mustEmbedUnimplementedCodeBattleServiceServer()
}

func RegisterCodeBattleServiceServer(s grpc.ServiceRegistrar, srv CodeBattleServiceServer) {
	// If the following call pancis, it indicates UnimplementedCodeBattleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CodeBattleService_ServiceDesc, srv)
}

func _CodeBattleService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeBattleServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CodeBattleService_GetEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeBattleServiceServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CodeBattleService_ServiceDesc is the grpc.ServiceDesc for CodeBattleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CodeBattleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "code_battle.CodeBattleService",
	HandlerType: (*CodeBattleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEvents",
			Handler:    _CodeBattleService_GetEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/code_battle.proto",
}
